// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3ckP-jmdTKm657LFDGsI_so_JSN3qbGs',
    appId: '1:725028676186:android:95022827cd693f50f62e63',
    messagingSenderId: '725028676186',
    projectId: 'gomhor-al-ahly',
    databaseURL: 'https://gomhor-al-ahly-default-rtdb.firebaseio.com',
    storageBucket: 'gomhor-al-ahly.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlI3SU_iIRFIzvyxfbwFvcbls7QggJp7I',
    appId: '1:725028676186:web:af6bd8363367fa1ef62e63',
    messagingSenderId: '725028676186',
    projectId: 'gomhor-al-ahly',
    authDomain: 'gomhor-al-ahly.firebaseapp.com',
    databaseURL: 'https://gomhor-al-ahly-default-rtdb.firebaseio.com',
    storageBucket: 'gomhor-al-ahly.firebasestorage.app',
    measurementId: 'G-L321EYVT1L',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6MZ69ajS44noRx3lRgskzA_tkEfj--WY',
    appId: '1:725028676186:ios:d6637ab1e913fc23f62e63',
    messagingSenderId: '725028676186',
    projectId: 'gomhor-al-ahly',
    databaseURL: 'https://gomhor-al-ahly-default-rtdb.firebaseio.com',
    storageBucket: 'gomhor-al-ahly.firebasestorage.app',
    androidClientId: '725028676186-n6fehe7icj9l6bvrr6c1sk70a588jcl7.apps.googleusercontent.com',
    iosClientId: '725028676186-b2avog6m2e2nsj2e9vp5kdsta7n8kutc.apps.googleusercontent.com',
    iosBundleId: 'com.example.gomhorAlahlyCleanNew',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6MZ69ajS44noRx3lRgskzA_tkEfj--WY',
    appId: '1:725028676186:ios:d6637ab1e913fc23f62e63',
    messagingSenderId: '725028676186',
    projectId: 'gomhor-al-ahly',
    databaseURL: 'https://gomhor-al-ahly-default-rtdb.firebaseio.com',
    storageBucket: 'gomhor-al-ahly.firebasestorage.app',
    androidClientId: '725028676186-n6fehe7icj9l6bvrr6c1sk70a588jcl7.apps.googleusercontent.com',
    iosClientId: '725028676186-b2avog6m2e2nsj2e9vp5kdsta7n8kutc.apps.googleusercontent.com',
    iosBundleId: 'com.example.gomhorAlahlyCleanNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlI3SU_iIRFIzvyxfbwFvcbls7QggJp7I',
    appId: '1:725028676186:web:83d57e6120e404fef62e63',
    messagingSenderId: '725028676186',
    projectId: 'gomhor-al-ahly',
    authDomain: 'gomhor-al-ahly.firebaseapp.com',
    databaseURL: 'https://gomhor-al-ahly-default-rtdb.firebaseio.com',
    storageBucket: 'gomhor-al-ahly.firebasestorage.app',
    measurementId: 'G-XE6L0B63F3',
  );

}